# Usa una imagen base de Node.js
FROM node:18-alpine

# Define el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código de la aplicación
COPY . .

# Expone el puerto que usa tu aplicación Node.js (ej. 3000)
EXPOSE 3000

# Comando para ejecutar la aplicación
CMD [ "node", "index.js" ]