name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/ansonjonel/mi-aplicacion-node:latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Permiso para leer el código del repositorio
      packages: write # ESTO ES LO CLAVE: Permiso para escribir en GHCR
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t $IMAGE_NAME .

    - name: Push Docker image
      run: docker push $IMAGE_NAME

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/gitops-demo-deployment gitops-demo=$IMAGE_NAME --namespace default
        kubectl rollout status deployment/gitops-demo-deployment --namespace default

