name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  # IMAGE_NAME: ghcr.io/ansonjonel/mi-aplicacion-node:latest
  # Cambia esto para usar el SHA del commit como tag
  # Esto asegura un tag único para cada push
  IMAGE_NAME_BASE: ghcr.io/ansonjonel/mi-aplicacion-node
  IMAGE_TAG: ${{ github.sha }} # Usará el hash completo del commit
  # Si prefieres un tag más corto (primeros 7 caracteres del hash):
  # IMAGE_TAG: ${{ github.sha_short }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Permiso para leer el código del repositorio
      packages: write # ESTO ES LO CLAVE: Permiso para escribir en GHCR
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        # password: ${{ secrets.GITHUB_TOKEN }}
        password: ${{ secrets.GHCR_PAT }} # Usa el secreto de tu PAT

    - name: Build Docker image
      #run: docker build -t $IMAGE_NAME .
      run: docker build -t ${{ env.IMAGE_NAME_BASE }}:${{ env.IMAGE_TAG }} .

    - name: Push Docker image
      #run: docker push $IMAGE_NAME
      run: docker push ${{ env.IMAGE_NAME_BASE }}:${{ env.IMAGE_TAG }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/gitops-demo-deployment gitops-demo=$IMAGE_NAME --namespace default
        kubectl rollout status deployment/gitops-demo-deployment --namespace default

